### ISSUE TITLE
Why I installed, the cursor on a line of JavaScript inside, there is no effect?

### ISSUE THREAD

**Issue by lufinka** [pranaygp/JS-live-debugger#1]

**Comment by pranaygp** [comment]
Can you please attach a screenshot? It'll help me try and recreate your issue.

**Comment by qbicsky** [comment]
Hi there! Is there any solution for this yet?
There is also no screenshot to make since there is nothing showing. :)

**Comment by pranaygp** [comment]
@qbconcept I'll need a bit more context to be able to figure out why nothing shows up. On example code I've tried this on, it's worked well, though I'm sure I could have missed an edge case. If you could provide me example code where you run into this issue for instance, I could take a look into it

**Comment by qbicsky** [comment]
Remember, I am learning. It is my 1st attempt to programming. So please don't judge. :)

edit: Problem might be related to some configuration issue. IDK.


[wisielec.zip](https://github.com/pranaygp/JS-live-debugger/files/1045713/wisielec.zip)

**Comment by pranaygp** [comment]
Can you please copy and past your code into a new comment on this thread. I'm not super comfortable with downloading a zip file

**Comment by qbicsky** [comment]
No problem. Code is here on github: https://github.com/qbconcept/001-hangman
If you specifically need code in a comment, then here it is:
> js
```javascript
const wikiurl = "https://pl.wikiquote.org/w/api.php?action=query&format=json&origin=*&prop=revisions%7Cinfo&"
                + "titles=Przys%C5%82owia+polskie&utf8=1&rvprop=content&rvlimit=1";
var entry = "",
    hiddenEntry = "",
    alphabetString = "AĄBCĆDEĘFGHIJKLŁMNŃOÓPQRSŚTUVWXYZŹŻ",
    alphabetArray = new Array(),
    alphabetGrid = "",
    fails = 0,
    successSound = document.createElement("audio"),
    failSound = document.createElement("audio"),
    i = 0;
successSound.src = "wav/yes.wav";
failSound.src = "wav/no.wav";
String.prototype.revealLetter = function (place, letter) {
    'use strict';
    if (place <= this.length - 1) {
        return this.substr(0, place) + letter + this.substr(place + 1);
    }
};
function entryGenerator () {
    'use strict';
    fetch(wikiurl)
    .then(function(response) {
        return response.json();
    })
    .then(function(data) {
        var rawQuery = data.query.pages["4974"].revisions["0"]["*"];
        rawQuery = rawQuery.replace(/\*{2}.*|==.*==|\[+.*\]+|{+.*}+|\*\s?|\s*\([^)]*\)/g, "");
        var query2array = rawQuery.split(/\n+/);
        var proverbs = query2array.splice(1, query2array.length);
        proverbs = proverbs.splice(0, proverbs.length-1);
        entry = proverbs[Math.floor(Math.random()*proverbs.length)];
        for (i = 0; i < entry.length; i += 1) {
            if (/\W/.test(entry.charAt(i)) && /[^ĄĆĘŁŃÓŚŹŻąćęłńóśźż]/.test(entry.charAt(i))) {
                hiddenEntry = hiddenEntry + entry.charAt(i);
            } else {
                hiddenEntry = hiddenEntry + "_";
            }
        }
        entry = entry.toUpperCase();
        printEntry();
    });
}
function startUp() {
    'use strict';
    entryGenerator();
    for (i = 0; i < alphabetString.length; i += 1) {
        alphabetArray[i] = alphabetString.charAt(i);
        alphabetGrid = alphabetGrid + "<div id=\"gpl-" + i + "\" class=\"letter button\" onclick=\"letterCheck("
                                    + i + ")\">" + alphabetArray[i] + "</div>";
        // In case of responsivity below won't work properly
        if ((i + 1) % 7 === 0) { alphabetGrid = alphabetGrid + "<div style='clear:both;'></div>"; }
    }
    document.getElementById("alphabet").innerHTML = alphabetGrid;
    document.getElementById("gallows").innerHTML = "<img src=\"img/s" + fails + ".jpg\" alt=\"\">";
}
function printEntry() {
    'use strict';
    document.getElementById("entry").innerHTML = hiddenEntry;
}
function letterCheck(no) {                                                                    /* exported letterCheck */
    'use strict';
    var success = false,
        letter = "gpl-" + no;
    for (i = 0; i < entry.length; i += 1) {
        if (entry.charAt(i) === alphabetString.charAt(no)) {
            hiddenEntry = hiddenEntry.revealLetter(i, alphabetString.charAt(no));
            success = true;
        }
    }
    if (success === true) {
        successSound.play();
        document.getElementById(letter).className += " letter-success";
        printEntry();
    } else {
        failSound.play();
        document.getElementById(letter).className += " letter-fail";
        fails += 1;
        document.getElementById("gallows").innerHTML = "<img src=\"img/s" + fails + ".jpg\" alt=\"\" />";
    }
    document.getElementById(letter).setAttribute("onClick", ";");
    if (entry === hiddenEntry) {
        document.getElementById("alphabet").innerHTML = "<span class=\"winner\">Brawo!</span><br /> <br />"
                                                        + "<span class=\"reset button\" onclick=\"location.reload()\">"
                                                        + "Gram ostatni raz!</span>";
    }
    if (fails >= 9) {
        document.getElementById("alphabet").innerHTML = "<span class=\"looser\">Wisisz!</span><br /><br />"
                                                        + "<span class=\"reset button\" onclick=\"location.reload()\">"
                                                        + "Gram ostatni raz!</span>";
    }
}
document.addEventListener('DOMContentLoaded', startUp);
```
> html
```html
<!DOCTYPE HTML>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <title>Wisielec</title>
    <link rel="stylesheet" href="style.css" type="text/css" />
<!--    <script type="text/javascript" src="losowy-cytat.js" defer></script>-->
    <script type="text/javascript" src="wisielec.js" defer></script>
</head>
<body>
    <div id="gallows-pole">
        <div id="entry"></div>
        <div id="game">
            <div id="gallows"></div>
            <div id="alphabet"></div>
        </div>
    </div>
</body>
</html>
```
>css
```css
html {
    height: 100vh;
    font-size: 62.5%;
    -webkit-user-select: none;
    user-select: none;
}
body {
    display: flex;
    flex-direction: column;
    margin: 0;
    padding: 0;
    background-color: black;
    min-height: 100vh;
    color: lightgray;
    font: 4rem "Courier New", monospace;
}
#gallows-pole {
    flex: 1;
}
#entry {
    padding: 1em 0;
    display: block;
    text-align: center;
    font-size: 5rem;
    letter-spacing: 0.5rem;
    font-weight: 700;
    min-height: 2.3rem;
}
#game {
    display: flex;
    flex-direction: row;
    margin: 0 auto;
}
#gallows {
    flex: 1;
    width: 50%;
    min-height: 280px;
    text-align: center;
}
#gallows img {
    width: 80%;
}
#alphabet {
    flex: 1;
    width: 50%;
}
.letter {
    float: left;
    width: 5rem;
    height: 5rem;
    margin: 0.5rem;
    text-align: center;
    cursor: pointer;
}
.letter:hover {
    background-color: #111;
    border-color: white;
    color: white;
}
.button {
    padding: 1.8rem;                        /* padding + border     */
    border: 0.2rem solid gray;              /* makes it even 2.0rem */
    border-radius: 2rem;
}
.letter-success {
    background: #003300 !important;
    color: #00C000 !important;
    border: 0.2rem solid #00C000 !important;
    cursor: default;
}
.letter-fail {
    background: #330000 !important;
    color: #C00000 !important;
    border: 0.2rem solid #C00000 !important;
    cursor: default;
}
.reset {
    cursor: pointer;
}
.reset:hover {
    color: white;
}
.winner {
    color: green;
    font-weight: 700;
}
.looser {
    color: #C00000;
    font-weight: 700;
}
```
